'use strict'
const router=require('express').Router()
const controller=require('./supplier-refunds.controller')
const rules=require('./supplier-refunds.rules')
const {authMiddleware,requirePermission}=require('../../middleware/auth')
const {PERMISSIONS:P}=require('../../constants/permissions')
const {validateBody}=require('../../utils/route')
router.use(authMiddleware)
router.get('/operations/:uuid',controller.own)
router.get('/backfill-applications/:uuid',controller.backfillApplication)
router.get('/source',requirePermission(P.SUPPLIER_REFUND_VIEW),controller.source)
router.get('/',requirePermission(P.SUPPLIER_REFUND_VIEW),controller.list)
router.get('/:id',requirePermission(P.SUPPLIER_REFUND_VIEW),controller.detail)
router.post('/',requirePermission(P.SUPPLIER_REFUND_CREATE),validateBody({parse:rules.createBody}),controller.create)
router.post('/:id/confirm',requirePermission(P.SUPPLIER_REFUND_CONFIRM),validateBody({parse:rules.actionBody}),controller.confirm)
router.post('/:id/regenerate-voucher',requirePermission(P.ACCOUNTING_VOUCHER_MANAGE),controller.regenerateVoucher)
router.post('/:id/receive',requirePermission(P.SUPPLIER_REFUND_RECEIVE),validateBody({parse:rules.receiveBody}),controller.receive)
router.post('/:id/cancel',requirePermission(P.SUPPLIER_REFUND_CREATE),validateBody({parse:rules.actionBody}),controller.cancel)
module.exports=router
