import { lazy } from 'react'

// ── PDA 子系统页面 ────────────────────────────────────────────────────────────
export const PdaLoginPage   = lazy(() => import('@/pages/pda/login'))
export const PdaIndexPage   = lazy(() => import('@/pages/pda'))
export const PdaPickingPage = lazy(() => import('@/pages/pda/picking'))
export const PdaTaskPage    = lazy(() => import('@/pages/pda/task'))
export const PdaInboundPage = lazy(() => import('@/pages/pda/inbound'))
export const PdaReceivePage = lazy(() => import('@/pages/pda/receive'))
export const PdaPutawayPage = lazy(() => import('@/pages/pda/putaway'))
export const PdaCheckPage   = lazy(() => import('@/pages/pda/check'))
export const PdaPackPage    = lazy(() => import('@/pages/pda/pack'))
export const PdaStockcheckPage = lazy(() => import('@/pages/pda/stockcheck'))
export const PdaSplitPage   = lazy(() => import('@/pages/pda/split'))
export const PdaFillPage    = lazy(() => import('@/pages/pda/fill'))
export const PdaPlasticBoxPage = lazy(() => import('@/pages/pda/plastic-box'))
export const PdaSplitRecoveryPage = lazy(() => import('@/pages/pda/split-recovery'))
export const PdaBindPage    = lazy(() => import('@/pages/pda/bind'))
export const PdaShipPage    = lazy(() => import('@/pages/pda/ship'))
export const PdaSortPage    = lazy(() => import('@/pages/pda/sort'))
export const PdaSaleReturnListPage = lazy(() => import('@/pages/pda/sale-return'))
export const PdaSaleReturnReceivePage = lazy(() => import('@/pages/pda/sale-return-receive'))
export const PdaSaleReturnPutawayPage = lazy(() => import('@/pages/pda/sale-return-putaway'))
export const PdaCancelReturnPage = lazy(() => import('@/pages/pda/cancel-return'))
export const PdaAdjustmentPage = lazy(() => import('@/pages/pda/adjustment'))
export const PdaTransferPage    = lazy(() => import('@/pages/pda/transfer'))
export const PdaTransferOutPage = lazy(() => import('@/pages/pda/transfer-out'))
export const PdaTransferInPage  = lazy(() => import('@/pages/pda/transfer-in'))
export const PdaInventoryQueryPage = lazy(() => import('@/pages/pda/inventory-query'))
