const assert = require('node:assert/strict')
const { configureTestEnvironment, validateTestEnvironment } = require('./helpers/testEnvironment')
configureTestEnvironment()
const mysql = require('../backend/node_modules/mysql2/promise')
async function main() {
  const conn = await mysql.createConnection({ ...validateTestEnvironment(), timezone: '+08:00' })
  await conn.query("SET time_zone='+08:00'")
  const transaction = { query: (...args) => conn.query(...args), beginTransaction: () => conn.query('SAVEPOINT fulfillment_service'), commit: () => conn.query('RELEASE SAVEPOINT fulfillment_service'), rollback: () => conn.query('ROLLBACK TO SAVEPOINT fulfillment_service'), release() {} }
  require.cache[require.resolve('../backend/src/config/db')] = { exports: { pool: { query: (...args) => conn.query(...args), getConnection: async () => transaction } } }
  const service = require('../backend/src/modules/fulfillment/fulfillment.service')
  require('../backend/src/modules/print-jobs/print-jobs.dispatch').startPrintJobSweeper = () => {}
  const sales = require('../backend/src/modules/sale/sale.service')
  const { syncDocument } = require('../backend/src/modules/fulfillment/fulfillment.worker')
  const { purchaseImpacts } = require('../backend/src/modules/fulfillment/fulfillment.delivery')
  const { PERMISSIONS: P } = require('../backend/src/constants/permissions')
  const prefix = `FUL${Date.now().toString(36)}`
  let seq = 0
  const code = () => `${prefix}${++seq}`
  const insert = async (sql, params = []) => Number((await conn.query(sql, params))[0].insertId)
  await conn.beginTransaction()
  try {
    const owner = await insert("INSERT INTO sys_users(username,password,real_name,role_id,role_name,is_active) VALUES(?,'!','履约测试',1,'管理员',1)", [code()])
    const user = { userId: owner, roleId: 1, realName: '履约测试', warehouseIds: null }
    const w1 = await insert("INSERT INTO inventory_warehouses(code,name) VALUES(?,'履约仓一')", [code()])
    const w2 = await insert("INSERT INTO inventory_warehouses(code,name) VALUES(?,'履约仓二')", [code()])
    const product = await insert("INSERT INTO product_items(code,name,unit) VALUES(?,'履约测试商品','件')", [code()])
    const po = await insert("INSERT INTO purchase_orders(order_no,supplier_id,supplier_name,warehouse_id,warehouse_name,status,operator_id,operator_name,expected_date) VALUES(?,1,'测试',?,'履约仓一',2,?,'履约测试','2000-01-01')", [code(), w1, owner])
    const pi = await insert("INSERT INTO purchase_order_items(order_id,product_id,product_code,product_name,unit,quantity,unit_price,amount) VALUES(?,?,?,'履约测试商品','件',10,1,10)", [po, product, code()])
    const so = await insert("INSERT INTO sale_orders(order_no,customer_id,customer_name,warehouse_id,warehouse_name,status,operator_id,operator_name) VALUES(?,1,'测试',?,'履约仓一',2,?,'履约测试')", [code(), w1, owner])
    const si = await insert("INSERT INTO sale_order_items(order_id,product_id,product_code,product_name,unit,warehouse_id,quantity,unit_price,amount,reserved_qty) VALUES(?,?,?,'履约测试商品','件',?,10,1,10,10)", [so, product, code(), w1])
    await conn.query('INSERT INTO sale_order_expected_bindings(sale_order_id,sale_order_item_id,purchase_order_id,purchase_item_id,product_id,warehouse_id,qty) VALUES(?,?,?,?,?,?,10)', [so, si, po, pi, product, w1])
    await conn.query("INSERT INTO stock_reservations(product_id,warehouse_id,qty,ref_type,ref_id,ref_no,status) VALUES(?,?,10,'sale_order',?,'test',1)", [product, w1, so])
    await conn.query('INSERT INTO inventory_stock(product_id,warehouse_id,quantity,reserved) VALUES(?,?,0,10)', [product, w1])
    await syncDocument('purchase', po)
    let doc = await service.getDocument('purchase', po, user)
    assert.equal(doc.issues.length, 1)
    assert.equal(Number(doc.issues[0].owner_id), owner)
    const issue = doc.issues[0]
    await assert.rejects(service.changeIssue('purchase', po, issue.id, { action: 'resolve', version: issue.version, result: '已联系' }, user, code()), /仍存在/)
    await syncDocument('purchase', po)
    assert.equal((await service.getDocument('purchase', po, user)).issues.length, 1, '重复同步不能重复事项')
    const dateKey = code()
    const body = { itemId: 0, date: '2099-01-10', processingDays: null, reason: '供应商改期' }
    await service.setDates('purchase', po, body, user, dateKey)
    await service.setDates('purchase', po, body, user, dateKey)
    const [[saved]] = await conn.query("SELECT COUNT(*) AS n FROM order_fulfillment_events WHERE document_type='purchase' AND document_id=? AND title='更新采购预计到货日期'", [po])
    assert.equal(Number(saved.n), 1, '日期重放只有一条事件')
    await syncDocument('purchase', po)
    doc = await service.getDocument('purchase', po, user)
    assert.equal(doc.issues[0].status, 'resolved')
    assert.equal(doc.commitments[0].originalDate, '2000-01-01')
    await service.setDates('sale', so, { itemId: 0, date: '2099-01-05', processingDays: null, reason: '客户确认' }, user, code())
    const sale = await service.getDocument('sale', so, user)
    assert.equal(sale.delivery.items[0].allDate, null)
    assert.equal(sale.delivery.items[0].delayed, true, '晚到采购且仓库时效未知仍预警')
    assert.equal(sale.delivery.items[0].shortage, 0)
    const manualKey = code()
    const manual = await service.createIssue('purchase', po, { title: '包装破损待确认', reason: '供应商跟进', dueDate: null }, user, manualKey)
    assert.equal((await service.createIssue('purchase', po, { title: '包装破损待确认', reason: '供应商跟进', dueDate: null }, user, manualKey)).id, manual.id)
    await service.changeIssue('purchase', po, manual.id, { action: 'assign', version: 1, ownerId: null, result: '转交岗位认领' }, user, code())
    await service.changeIssue('purchase', po, manual.id, { action: 'claim', version: 2 }, user, code())
    await assert.rejects(service.changeIssue('purchase', po, manual.id, { action: 'claim', version: 2 }, user, code()), /已被其他人更新/)
    await service.changeIssue('purchase', po, manual.id, { action: 'resolve', version: 3, result: '包装确认无误' }, user, code())
    const denied = { userId: owner, roleId: 2, permissions: [P.PURCHASE_ORDER_VIEW], warehouseIds: [w1] }
    await assert.rejects(service.createIssue('purchase', po, { title: '越权', reason: '越权', dueDate: null }, denied, code()), e => e.statusCode === 403)
    await assert.rejects(service.getDocument('purchase', po, { ...denied, warehouseIds: [w2] }), e => e.statusCode === 403)
    await insert("INSERT INTO sale_order_items(order_id,product_id,product_code,product_name,unit,warehouse_id,quantity,unit_price,amount) VALUES(?,?,?,'跨仓商品','件',?,1,1,1)", [so, product, code(), w2])
    const limitedSale = { ...denied, permissions: [P.PURCHASE_ORDER_VIEW, P.SALE_ORDER_VIEW] }
    assert.equal((await purchaseImpacts(conn, po, limitedSale)).length, 0, '混仓销售不可从采购影响清单旁路读取')
    const filtered = await service.listIssues({ keyword: '测试', documentType: 'purchase', pageSize: 99999, filter: 'resolved' }, user)
    assert.equal(filtered.pagination.pageSize, 500)
    assert.ok(filtered.list.some(i => Number(i.document_id) === po))
    assert.ok(filtered.list.every(i => i.document_type === 'purchase'))
    assert.ok(filtered.list.every(i => i.documentNo && i.partyName === '测试' && i.warehouseName === '履约仓一'))
    assert.equal(filtered.pagination.total, filtered.list.length)
    const limitedIssues = await service.listIssues({ documentType: 'sale' }, limitedSale)
    assert.ok(!limitedIssues.list.some(i => Number(i.document_id) === so), '批量名称搜索不得泄露跨仓销售')
    assert.equal((await service.listIssues({ keyword: "' OR 1=1 --" }, user)).list.length, 0)
    const { createRefreshProcessor } = require('../backend/src/modules/fulfillment/fulfillment.refresh')
    const related = []
    const processRefresh = createRefreshProcessor({ pool: { query: (...args) => conn.query(...args) }, syncDocument, notify: (type, id) => related.push({ type, id: Number(id) }) })
    await conn.query('UPDATE purchase_orders SET expected_date=? WHERE id=?', ['2000-01-01', po])
    await processRefresh({ type: 'purchase', id: po, expand: true, cursor: 0 })
    assert.ok(related.some(i => i.type === 'sale' && i.id === so), '采购变化触达依赖销售')
    await conn.query('UPDATE sale_order_expected_bindings SET released_at=NOW() WHERE sale_order_id=?', [so])
    related.length = 0
    await processRefresh({ type: 'purchase', id: po, expand: true, cursor: 0 })
    assert.ok(related.some(i => i.id === so), '已解除绑定仍按商品仓库刷新候选供应')
    const task = await insert("INSERT INTO warehouse_tasks(task_no,sale_order_id,sale_order_no,customer_id,customer_name,warehouse_id,warehouse_name,status) VALUES(?,?,'test',1,'测试',?,'履约仓一',7)", [code(), so, w1])
    await syncDocument('sale', so)
    assert.ok((await service.getDocument('sale', so, user)).issues.some(i => i.status !== 'resolved'))
    await conn.query('UPDATE sale_orders SET status=4 WHERE id=?', [so])
    await processRefresh({ type: 'warehouse', id: task, expand: true, cursor: 0 })
    assert.ok((await service.getDocument('sale', so, user)).issues.every(i => i.status === 'resolved'), '最后出库关闭已结束销售事项，不等30秒扫描')
    const extraSales = []
    for (let index = 0; index < 27; index++) {
      const id = await insert("INSERT INTO sale_orders(order_no,customer_id,customer_name,warehouse_id,warehouse_name,status,operator_id,operator_name) VALUES(?,1,'分页客户',?,'履约仓一',2,?,'履约测试')", [code(), w1, owner])
      await insert("INSERT INTO sale_order_items(order_id,product_id,product_code,product_name,unit,quantity,unit_price,amount) VALUES(?,?,?,'分页商品','件',1,1,1)", [id, product, code()])
      extraSales.push(id)
    }
    related.length = 0
    const nextPage = await processRefresh({ type: 'purchase', id: po, expand: true, cursor: 0 })
    assert.equal(related.length, 25, '一次供应依赖查询最多通知25单')
    assert.ok(nextPage)
    const lastPage = await processRefresh({ type: 'purchase', id: po, expand: true, cursor: nextPage })
    assert.equal(lastPage, null)
    assert.deepEqual(related.map(i => i.id), extraSales, '唯一ID游标连续覆盖所有销售')
    const inboundId = await insert("INSERT INTO inbound_tasks(task_no,purchase_order_id,warehouse_id,warehouse_name,status) VALUES(?,?,?,'履约仓一',4)", [code(), po, w1])
    related.length = 0
    const inboundSales = await processRefresh({ type: 'inbound', id: inboundId, expand: true, cursor: 0 })
    assert.deepEqual(related, [{ type: 'purchase', id: po }], '收货提交关联采购刷新在独立有界阶段')
    assert.equal(inboundSales.stage, 'sale')
    const runtime = require('../backend/src/modules/fulfillment/fulfillment.refresh')
    const beforeRejected = runtime.getRefreshStats()
    await assert.rejects(service.setDates('purchase', po, { itemId: 99, date: '2099-01-01' }, user, code()), /整单/)
    const afterRejected = runtime.getRefreshStats()
    assert.equal(afterRejected.pending, beforeRejected.pending, '业务事务回滚不新增队列')
    assert.equal(afterRejected.merged, beforeRejected.merged, '业务事务回滚不合并已有队列')
    const todo = await service.listIssues({ page: 1, pageSize: 200 }, user)
    assert.ok(todo.summary)
    const noAccess = await service.listIssues({ page: 1, pageSize: 200 }, { roleId: 2, userId: owner, permissions: [] })
    assert.equal(noAccess.list.length, 0)
    const customer = await insert("INSERT INTO sale_customers(code,name) VALUES(?,'交期保留客户')", [code()])
    const draft = await sales.create({ customerId: customer, warehouseId: w1, items: [{ productId: product, quantity: 10, unitPrice: 1 }], operator: user, requestKey: code() })
    const [[originalItem]] = await conn.query('SELECT id FROM sale_order_items WHERE order_id=?', [draft.id])
    await service.setDates('sale', draft.id, { itemId: originalItem.id, date: '2099-02-10', processingDays: 2, reason: '商品交期单独确认' }, user, code())
    await sales.update(draft.id, { customerId: customer, warehouseId: w1, remark: '修改备注', items: [{ productId: product, quantity: 12, unitPrice: 1 }], operator: user })
    const edited = await service.getDocument('sale', draft.id, user)
    assert.notEqual(edited.delivery.items[0].id, originalItem.id)
    assert.equal(edited.delivery.items[0].promisedDate, '2099-02-10', '重建同商品同仓明细必须保留覆盖交期')
    assert.equal(edited.delivery.items[0].processingDays, 2)
    await sales.update(draft.id, { customerId: customer, warehouseId: w2, items: [{ productId: product, quantity: 12, unitPrice: 1 }], operator: user })
    assert.equal((await service.getDocument('sale', draft.id, user)).delivery.items[0].promisedDate, null, '改仓的新增需求不继承原仓明细承诺')
    const productX = await insert("INSERT INTO product_items(code,name,unit) VALUES(?,'旧维度商品X','件')", [code()])
    const productY = await insert("INSERT INTO product_items(code,name,unit) VALUES(?,'保留商品Y','件')", [code()])
    const { createContainer, syncStockFromContainers, SOURCE_TYPE } = require('../backend/src/engine/containerEngine')
    for (const productId of [productX, productY]) {
      await createContainer(conn, { productId, warehouseId: w1, initialQty: 1, unit: '件', sourceType: SOURCE_TYPE.TRANSFER, sourceRefId: 1, sourceRefType: 'test_seed', sourceRefNo: code() })
      await syncStockFromContainers(conn, productId, w1)
    }
    const item = productId => ({ productId, quantity: 1, unitPrice: 1 })
    const orderA = await sales.create({ customerId: customer, warehouseId: w1, items: [item(productX), item(productY)], operator: user, requestKey: code() })
    await sales.reserveStock(orderA.id, user, [], { requestKey: code() })
    const orderB = await sales.create({ customerId: customer, warehouseId: w1, items: [item(productX)], operator: user, requestKey: code() })
    async function drainRefresh() {
      for (let round = 0; round < 100 && runtime.getRefreshStats().pending; round++) await runtime.runFulfillmentRefresh()
      assert.equal(runtime.getRefreshStats().pending, 0, '有限通知队列已处理完成')
    }
    await drainRefresh()
    assert.ok((await service.getDocument('sale', orderB.id, user)).issues.some(i => i.status !== 'resolved' && i.source_key.startsWith('shortage:')))
    await sales.requestAdjustment(orderA.id, { items: [item(productY)], operator: user, requestKey: code() })
    await drainRefresh()
    assert.ok((await service.getDocument('sale', orderB.id, user)).issues.every(i => i.status === 'resolved'), 'A删X留Y释放实物后，B缺X事项必须通过提交队列解除')
    const mover = await sales.create({ customerId: customer, warehouseId: w1, items: [item(productX)], operator: user, requestKey: code() })
    await sales.reserveStock(mover.id, user, [], { requestKey: code() })
    await drainRefresh()
    assert.ok((await service.getDocument('sale', orderB.id, user)).issues.some(i => i.status !== 'resolved'))
    const beforeInvalidMove = runtime.getRefreshStats()
    await assert.rejects(sales.requestAdjustment(mover.id, { items: [item(9007199254740991)], operator: user, requestKey: code() }))
    assert.equal(runtime.getRefreshStats().pending, beforeInvalidMove.pending, '捕获旧维度后回滚不发布通知')
    assert.equal(runtime.getRefreshStats().merged, beforeInvalidMove.merged)
    const moveKey = code()
    const moveBody = { items: [{ ...item(productX), warehouseId: w2 }], operator: user, requestKey: moveKey }
    await sales.requestAdjustment(mover.id, moveBody)
    await drainRefresh()
    assert.ok((await service.getDocument('sale', orderB.id, user)).issues.every(i => i.status === 'resolved'), '同商品改仓后，旧仓依赖销售也及时解除')
    const beforeReplay = runtime.getRefreshStats()
    await sales.requestAdjustment(mover.id, moveBody)
    assert.equal(runtime.getRefreshStats().pending, beforeReplay.pending, '改单重放不重新发布维度通知')
    assert.equal(runtime.getRefreshStats().merged, beforeReplay.merged)
    const transferId = await insert("INSERT INTO transfer_orders(order_no,from_warehouse_id,from_warehouse_name,to_warehouse_id,to_warehouse_name,status,operator_id,operator_name) VALUES(?,?,'一仓',?,'二仓',1,?,'履约测试')", [code(), w1, w2, owner])
    await insert("INSERT INTO transfer_order_items(order_id,product_id,product_code,product_name,unit,quantity) VALUES(?,?,?,'X','件',1)", [transferId, productX, code()])
    assert.deepEqual((await runtime.captureDimensions(conn, 'transfer', transferId)).pairs, [`${productX}:${w1}`, `${productX}:${w2}`], '调拨旧维度包含两端且去重')
    // 在专用测试连接上验证真实COMMIT/ROLLBACK可见性；临时表随连接自动清除。
    const committed = []
    const commit = require('../backend/src/modules/fulfillment/fulfillment.refresh-queue').createCommitNotifier((type, id) => committed.push({ type, id }))
    const commitConn = await mysql.createConnection({ ...validateTestEnvironment(), timezone: '+08:00' })
    try {
      await commitConn.query('CREATE TEMPORARY TABLE fulfillment_notify_probe(id INT PRIMARY KEY) ENGINE=InnoDB')
      await commitConn.beginTransaction()
      await commitConn.query('INSERT INTO fulfillment_notify_probe VALUES(1)')
      await commit(commitConn, 'sale', 1)
      const [[visible]] = await commitConn.query('SELECT COUNT(*) AS total FROM fulfillment_notify_probe')
      assert.equal(Number(visible.total), 1)
      assert.deepEqual(committed, [{ type: 'sale', id: 1 }])
      await commitConn.beginTransaction()
      await commitConn.query('INSERT INTO fulfillment_notify_probe VALUES(2)')
      await commitConn.rollback()
      const [[rolledBack]] = await commitConn.query('SELECT COUNT(*) AS total FROM fulfillment_notify_probe')
      assert.equal(Number(rolledBack.total), 1)
      assert.equal(committed.length, 1)
    } finally { await commitConn.end() }
    console.log('PASS 履约 MySQL 回归：自动发现/幂等/关闭保护/自动解除/交期快照/延期影响/认领转派/版本冲突/权限与混仓隔离')
  } finally { await conn.rollback(); await conn.end() }
}
main().then(() => {
  // 当前回归用保存点隔离fixture；并发授信必须在独立进程使用真实连接池和真实COMMIT。
  require('node:child_process').execFileSync(process.execPath, [require('node:path').join(__dirname, 'fulfillment-credit-concurrency.smoke.test.js')], { stdio: 'inherit', env: process.env })
}).catch(error => { console.error(error.message); process.exitCode = 1 })
