const assert = require('node:assert/strict')
const { configureTestEnvironment, validateTestEnvironment } = require('./helpers/testEnvironment')
configureTestEnvironment()
const mysql = require('../backend/node_modules/mysql2/promise')
async function main() {
  const conn = await mysql.createConnection({ ...validateTestEnvironment(), timezone: '+08:00' })
  await conn.query("SET time_zone='+08:00'")
  const transaction = { query: (...args) => conn.query(...args), beginTransaction: () => conn.query('SAVEPOINT fulfillment_service'), commit: () => conn.query('RELEASE SAVEPOINT fulfillment_service'), rollback: () => conn.query('ROLLBACK TO SAVEPOINT fulfillment_service'), release() {} }
  require.cache[require.resolve('../backend/src/config/db')] = { exports: { pool: { query: (...args) => conn.query(...args), getConnection: async () => transaction } } }
  const service = require('../backend/src/modules/fulfillment/fulfillment.service')
  require('../backend/src/modules/print-jobs/print-jobs.dispatch').startPrintJobSweeper = () => {}
  const sales = require('../backend/src/modules/sale/sale.service')
  const { syncDocument } = require('../backend/src/modules/fulfillment/fulfillment.worker')
  const { purchaseImpacts } = require('../backend/src/modules/fulfillment/fulfillment.delivery')
  const { PERMISSIONS: P } = require('../backend/src/constants/permissions')
  const prefix = `FUL${Date.now().toString(36)}`
  let seq = 0
  const code = () => `${prefix}${++seq}`
  const insert = async (sql, params = []) => Number((await conn.query(sql, params))[0].insertId)
  await conn.beginTransaction()
  try {
    const owner = await insert("INSERT INTO sys_users(username,password,real_name,role_id,role_name,is_active) VALUES(?,'!','履约测试',1,'管理员',1)", [code()])
    const user = { userId: owner, roleId: 1, realName: '履约测试', warehouseIds: null }
    const w1 = await insert("INSERT INTO inventory_warehouses(code,name) VALUES(?,'履约仓一')", [code()])
    const w2 = await insert("INSERT INTO inventory_warehouses(code,name) VALUES(?,'履约仓二')", [code()])
    const product = await insert("INSERT INTO product_items(code,name,unit) VALUES(?,'履约测试商品','件')", [code()])
    const po = await insert("INSERT INTO purchase_orders(order_no,supplier_id,supplier_name,warehouse_id,warehouse_name,status,operator_id,operator_name,expected_date) VALUES(?,1,'测试',?,'履约仓一',2,?,'履约测试','2000-01-01')", [code(), w1, owner])
    const pi = await insert("INSERT INTO purchase_order_items(order_id,product_id,product_code,product_name,unit,quantity,unit_price,amount) VALUES(?,?,?,'履约测试商品','件',10,1,10)", [po, product, code()])
    const so = await insert("INSERT INTO sale_orders(order_no,customer_id,customer_name,warehouse_id,warehouse_name,status,operator_id,operator_name) VALUES(?,1,'测试',?,'履约仓一',2,?,'履约测试')", [code(), w1, owner])
    const si = await insert("INSERT INTO sale_order_items(order_id,product_id,product_code,product_name,unit,warehouse_id,quantity,unit_price,amount,reserved_qty) VALUES(?,?,?,'履约测试商品','件',?,10,1,10,10)", [so, product, code(), w1])
    await conn.query('INSERT INTO sale_order_expected_bindings(sale_order_id,sale_order_item_id,purchase_order_id,purchase_item_id,product_id,warehouse_id,qty) VALUES(?,?,?,?,?,?,10)', [so, si, po, pi, product, w1])
    await conn.query("INSERT INTO stock_reservations(product_id,warehouse_id,qty,ref_type,ref_id,ref_no,status) VALUES(?,?,10,'sale_order',?,'test',1)", [product, w1, so])
    await conn.query('INSERT INTO inventory_stock(product_id,warehouse_id,quantity,reserved) VALUES(?,?,0,10)', [product, w1])
    await syncDocument('purchase', po)
    let doc = await service.getDocument('purchase', po, user)
    assert.equal(doc.issues.length, 1)
    assert.equal(Number(doc.issues[0].owner_id), owner)
    const issue = doc.issues[0]
    await assert.rejects(service.changeIssue('purchase', po, issue.id, { action: 'resolve', version: issue.version, result: '已联系' }, user, code()), /仍存在/)
    await syncDocument('purchase', po)
    assert.equal((await service.getDocument('purchase', po, user)).issues.length, 1, '重复同步不能重复事项')
    const dateKey = code()
    const body = { itemId: 0, date: '2099-01-10', processingDays: null, reason: '供应商改期' }
    await service.setDates('purchase', po, body, user, dateKey)
    await service.setDates('purchase', po, body, user, dateKey)
    const [[saved]] = await conn.query("SELECT COUNT(*) AS n FROM order_fulfillment_events WHERE document_type='purchase' AND document_id=? AND title='更新采购预计到货日期'", [po])
    assert.equal(Number(saved.n), 1, '日期重放只有一条事件')
    await syncDocument('purchase', po)
    doc = await service.getDocument('purchase', po, user)
    assert.equal(doc.issues[0].status, 'resolved')
    assert.equal(doc.commitments[0].originalDate, '2000-01-01')
    await service.setDates('sale', so, { itemId: 0, date: '2099-01-05', processingDays: null, reason: '客户确认' }, user, code())
    const sale = await service.getDocument('sale', so, user)
    assert.equal(sale.delivery.items[0].allDate, null)
    assert.equal(sale.delivery.items[0].delayed, true, '晚到采购且仓库时效未知仍预警')
    assert.equal(sale.delivery.items[0].shortage, 0)
    const manualKey = code()
    const manual = await service.createIssue('purchase', po, { title: '包装破损待确认', reason: '供应商跟进', dueDate: null }, user, manualKey)
    assert.equal((await service.createIssue('purchase', po, { title: '包装破损待确认', reason: '供应商跟进', dueDate: null }, user, manualKey)).id, manual.id)
    await service.changeIssue('purchase', po, manual.id, { action: 'assign', version: 1, ownerId: null, result: '转交岗位认领' }, user, code())
    await service.changeIssue('purchase', po, manual.id, { action: 'claim', version: 2 }, user, code())
    await assert.rejects(service.changeIssue('purchase', po, manual.id, { action: 'claim', version: 2 }, user, code()), /已被其他人更新/)
    await service.changeIssue('purchase', po, manual.id, { action: 'resolve', version: 3, result: '包装确认无误' }, user, code())
    const denied = { userId: owner, roleId: 2, permissions: [P.PURCHASE_ORDER_VIEW], warehouseIds: [w1] }
    await assert.rejects(service.createIssue('purchase', po, { title: '越权', reason: '越权', dueDate: null }, denied, code()), e => e.statusCode === 403)
    await assert.rejects(service.getDocument('purchase', po, { ...denied, warehouseIds: [w2] }), e => e.statusCode === 403)
    await insert("INSERT INTO sale_order_items(order_id,product_id,product_code,product_name,unit,warehouse_id,quantity,unit_price,amount) VALUES(?,?,?,'跨仓商品','件',?,1,1,1)", [so, product, code(), w2])
    const limitedSale = { ...denied, permissions: [P.PURCHASE_ORDER_VIEW, P.SALE_ORDER_VIEW] }
    assert.equal((await purchaseImpacts(conn, po, limitedSale)).length, 0, '混仓销售不可从采购影响清单旁路读取')
    const todo = await service.listIssues({ page: 1, pageSize: 200 }, user)
    assert.ok(todo.summary)
    const noAccess = await service.listIssues({ page: 1, pageSize: 200 }, { roleId: 2, userId: owner, permissions: [] })
    assert.equal(noAccess.list.length, 0)
    const customer = await insert("INSERT INTO sale_customers(code,name) VALUES(?,'交期保留客户')", [code()])
    const draft = await sales.create({ customerId: customer, warehouseId: w1, items: [{ productId: product, quantity: 10, unitPrice: 1 }], operator: user, requestKey: code() })
    const [[originalItem]] = await conn.query('SELECT id FROM sale_order_items WHERE order_id=?', [draft.id])
    await service.setDates('sale', draft.id, { itemId: originalItem.id, date: '2099-02-10', processingDays: 2, reason: '商品交期单独确认' }, user, code())
    await sales.update(draft.id, { customerId: customer, warehouseId: w1, remark: '修改备注', items: [{ productId: product, quantity: 12, unitPrice: 1 }], operator: user })
    const edited = await service.getDocument('sale', draft.id, user)
    assert.notEqual(edited.delivery.items[0].id, originalItem.id)
    assert.equal(edited.delivery.items[0].promisedDate, '2099-02-10', '重建同商品同仓明细必须保留覆盖交期')
    assert.equal(edited.delivery.items[0].processingDays, 2)
    await sales.update(draft.id, { customerId: customer, warehouseId: w2, items: [{ productId: product, quantity: 12, unitPrice: 1 }], operator: user })
    assert.equal((await service.getDocument('sale', draft.id, user)).delivery.items[0].promisedDate, null, '改仓的新增需求不继承原仓明细承诺')
    console.log('PASS 履约 MySQL 回归：自动发现/幂等/关闭保护/自动解除/交期快照/延期影响/认领转派/版本冲突/权限与混仓隔离')
  } finally { await conn.rollback(); await conn.end() }
}
main().catch(error => { console.error(error.message); process.exitCode = 1 })
