const { app, BrowserWindow, ipcMain } = require('electron')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { pathToFileURL } = require('node:url')
const { createRendererGuard } = require('../desktop/lib/rendererSecurity')
const guard = createRendererGuard()
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'flowcube-electron-smoke-'))
app.setPath('userData', path.join(dir, 'user-data'))
fs.writeFileSync(path.join(dir, 'index.html'), '<!doctype html><title>Electron regression</title><p>Smoke</p>')
fs.writeFileSync(path.join(dir, 'preload.cjs'), "const {contextBridge,ipcRenderer}=require('electron');contextBridge.exposeInMainWorld('smoke',{probe:()=>ipcRenderer.invoke('smoke:probe')})")
ipcMain.handle('smoke:probe', event => { if (!guard.isTrusted(event)) throw new Error('untrusted'); return 'trusted' })
app.whenReady().then(async () => {
 const win = new BrowserWindow({ show:false, webPreferences:{ preload:path.join(dir,'preload.cjs'), nodeIntegration:false, contextIsolation:true } })
 const url = pathToFileURL(path.join(dir,'index.html')).href
 guard.register(win.webContents,url)
 win.webContents.on('will-navigate',(event,target)=>{if(!guard.allowsNavigation(win.webContents,target))event.preventDefault()})
 win.webContents.setWindowOpenHandler(()=>({action:'deny'}))
 await win.loadURL(url+'#/')
 const ipc = await win.webContents.executeJavaScript('window.smoke.probe()')
 if(ipc!=='trusted') throw new Error('preload IPC failed')
 const isolated = await win.webContents.executeJavaScript('typeof require === "undefined" && typeof process === "undefined"')
 if(!isolated) throw new Error('node isolation failed')
 await win.webContents.executeJavaScript('window.location.hash="/sale"')
 if(await win.webContents.executeJavaScript('window.smoke.probe()')!=='trusted') throw new Error('hash routing failed')
 await win.webContents.executeJavaScript('window.location.href="https://example.invalid"')
 await new Promise(r=>setTimeout(r,200))
 if(!win.webContents.getURL().startsWith(url+'#')) throw new Error('external navigation escaped')
 const printers = await win.webContents.getPrintersAsync()
 console.log(JSON.stringify({electron:process.versions.electron,preloadIPC:true,nodeIsolation:true,hashRouting:true,navigationBlocked:true,printerEnumeration:Array.isArray(printers)}))
 win.destroy();fs.rmSync(dir,{recursive:true,force:true});app.exit(0)
}).catch(err=>{console.error(err.message);app.exit(1)})
