const { Router } = require('express')
const ctrl = require('./sale.controller')
const { authMiddleware, requirePermission } = require('../../middleware/auth')
const { PERMISSIONS } = require('../../constants/permissions')
const { validateBody } = require('../../utils/route')
const { createSaleSchema, reserveSaleSchema, releaseSaleSchema, shipSaleSchema,commercialPreviewSchema,commercialActionSchema } = require('./sale.contracts')
const router = Router()
router.use(authMiddleware)
router.get('/',           requirePermission(PERMISSIONS.SALE_ORDER_VIEW), ctrl.list)
router.get('/:id',        requirePermission(PERMISSIONS.SALE_ORDER_VIEW), ctrl.detail)
router.get('/:id/reserve-preview', requirePermission(PERMISSIONS.SALE_ORDER_RESERVE), ctrl.reservePreview)
router.post('/:id/commercial-preview', requirePermission(PERMISSIONS.SALE_ORDER_UPDATE), requirePermission(PERMISSIONS.PRODUCT_VIEW),validateBody(commercialPreviewSchema),ctrl.commercialPreview)
router.post('/',          requirePermission(PERMISSIONS.SALE_ORDER_CREATE), validateBody(createSaleSchema), ctrl.create)
router.put('/:id',        requirePermission(PERMISSIONS.SALE_ORDER_UPDATE), validateBody(createSaleSchema), ctrl.update)
router.put('/:id/adjust', requirePermission(PERMISSIONS.SALE_ORDER_UPDATE), validateBody(createSaleSchema), ctrl.adjust)
router.post('/:id/reserve',  requirePermission(PERMISSIONS.SALE_ORDER_RESERVE), validateBody(reserveSaleSchema), ctrl.reserve)
router.post('/:id/release',  requirePermission(PERMISSIONS.SALE_ORDER_RELEASE), validateBody(releaseSaleSchema), ctrl.release)
router.post('/:id/ship',     requirePermission(PERMISSIONS.SALE_ORDER_SHIP), validateBody(shipSaleSchema), ctrl.ship)
router.post('/:id/cancel',   requirePermission(PERMISSIONS.SALE_ORDER_CANCEL),validateBody(commercialActionSchema), ctrl.cancel)
router.delete('/:id',        requirePermission(PERMISSIONS.SALE_ORDER_DELETE),validateBody(commercialActionSchema), ctrl.del)
module.exports = router
