-- FlowCube ERP - Migration 004
-- 商品档案与供应商表（基础版本，后续字段由 migrate.js 补齐）

CREATE TABLE IF NOT EXISTS `product_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL COMMENT '商品编码',
  `name` VARCHAR(150) NOT NULL COMMENT '商品名称',
  `category_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '分类ID',
  `unit` VARCHAR(20) NOT NULL DEFAULT '个' COMMENT '单位',
  `spec` VARCHAR(100) DEFAULT NULL COMMENT '规格',
  `barcode` VARCHAR(100) DEFAULT NULL COMMENT '条码',
  `cost_price` DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '成本价',
  `sale_price` DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '售价',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品档案表';

CREATE TABLE IF NOT EXISTS `supply_suppliers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL COMMENT '供应商编码',
  `name` VARCHAR(100) NOT NULL COMMENT '供应商名称',
  `contact` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `address` VARCHAR(200) DEFAULT NULL COMMENT '地址',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商表';
