-- Formalized from migrate.js seedDefaultPrintTemplates. Keep idempotent by (type, name).

INSERT INTO print_templates (name, type, paper_size, layout_json, is_default)
SELECT '默认销售订单模板', 1, 'A4', '{"elements":[{"id":"s_title","type":"title","fieldKey":"title","label":"销售订单","x":25,"y":8,"width":160,"height":10,"fontSize":18,"fontWeight":"bold","textAlign":"center","border":false},{"id":"s_no","type":"text","fieldKey":"orderNo","label":"单据编号","x":110,"y":22,"width":90,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"right","border":false},{"id":"s_date","type":"text","fieldKey":"orderDate","label":"单据日期","x":110,"y":30,"width":90,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"right","border":false},{"id":"s_op","type":"text","fieldKey":"operator","label":"经办人","x":110,"y":38,"width":90,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"right","border":false},{"id":"s_cust","type":"text","fieldKey":"customerName","label":"客户名称","x":5,"y":22,"width":100,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"s_wh","type":"text","fieldKey":"warehouseName","label":"仓库","x":5,"y":30,"width":100,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"s_div1","type":"divider","fieldKey":"divider","label":"分隔线","x":5,"y":47,"width":198,"height":3,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"s_rname","type":"text","fieldKey":"receiverName","label":"收货人","x":5,"y":52,"width":50,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"s_rphone","type":"text","fieldKey":"receiverPhone","label":"联系电话","x":60,"y":52,"width":70,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"s_raddr","type":"text","fieldKey":"receiverAddress","label":"收货地址","x":5,"y":60,"width":198,"height":6,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"s_div2","type":"divider","fieldKey":"divider","label":"分隔线","x":5,"y":69,"width":198,"height":3,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"s_table","type":"table","fieldKey":"itemsTable","label":"商品明细","x":5,"y":74,"width":198,"height":100,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":true,"tableColumns":["code","name","unit","qty","price","amount"]},{"id":"s_total","type":"text","fieldKey":"totalAmount","label":"金额合计","x":120,"y":178,"width":83,"height":8,"fontSize":12,"fontWeight":"bold","textAlign":"right","border":false},{"id":"s_remark","type":"text","fieldKey":"remark","label":"备注","x":5,"y":190,"width":198,"height":14,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":true}]}', 1
WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'print_templates')
  AND NOT EXISTS (SELECT 1 FROM print_templates WHERE type = 1 AND name = '默认销售订单模板');

INSERT INTO print_templates (name, type, paper_size, layout_json, is_default)
SELECT '默认货架条码标签模板', 5, 'thermal80', '{"elements":[{"id":"lb5_bc","type":"barcode","fieldKey":"rack_barcode","label":"货架条码","x":4,"y":4,"width":72,"height":14,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb5_rc","type":"text","fieldKey":"rack_code","label":"货架编码","x":4,"y":22,"width":72,"height":7,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb5_z","type":"text","fieldKey":"zone","label":"库区","x":4,"y":32,"width":72,"height":7,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb5_n","type":"text","fieldKey":"name","label":"名称","x":4,"y":41,"width":72,"height":14,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false}]}', 1
WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'print_templates')
  AND NOT EXISTS (SELECT 1 FROM print_templates WHERE type = 5 AND name = '默认货架条码标签模板');

INSERT INTO print_templates (name, type, paper_size, layout_json, is_default)
SELECT '默认库存条码标签模板', 6, 'thermal80', '{"elements":[{"id":"lb6_bc","type":"barcode","fieldKey":"container_code","label":"库存条码","x":4,"y":4,"width":72,"height":14,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb6_pn","type":"text","fieldKey":"product_name","label":"品名","x":4,"y":22,"width":72,"height":10,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb6_q","type":"text","fieldKey":"qty","label":"数量","x":4,"y":36,"width":72,"height":7,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false}]}', 1
WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'print_templates')
  AND NOT EXISTS (SELECT 1 FROM print_templates WHERE type = 6 AND name = '默认库存条码标签模板');

INSERT INTO print_templates (name, type, paper_size, layout_json, is_default)
SELECT '默认物流条码标签模板', 7, 'thermal80', '{"elements":[{"id":"lb7_bc","type":"barcode","fieldKey":"box_code","label":"物流条码","x":4,"y":4,"width":72,"height":14,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb7_tn","type":"text","fieldKey":"task_no","label":"任务号","x":4,"y":22,"width":72,"height":7,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb7_cn","type":"text","fieldKey":"customer_name","label":"客户","x":4,"y":32,"width":72,"height":8,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb7_sm","type":"text","fieldKey":"summary","label":"摘要","x":4,"y":43,"width":72,"height":14,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false}]}', 1
WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'print_templates')
  AND NOT EXISTS (SELECT 1 FROM print_templates WHERE type = 7 AND name = '默认物流条码标签模板');

INSERT INTO print_templates (name, type, paper_size, layout_json, is_default)
SELECT '默认产品条码标签模板', 8, 'thermal80', '{"elements":[{"id":"lb8_bc","type":"barcode","fieldKey":"product_code","label":"产品条码","x":4,"y":4,"width":72,"height":14,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb8_pn","type":"text","fieldKey":"product_name","label":"产品名称","x":4,"y":22,"width":72,"height":10,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb8_sp","type":"text","fieldKey":"spec","label":"规格","x":4,"y":36,"width":72,"height":7,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false}]}', 1
WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'print_templates')
  AND NOT EXISTS (SELECT 1 FROM print_templates WHERE type = 8 AND name = '默认产品条码标签模板');

INSERT INTO print_templates (name, type, paper_size, layout_json, is_default)
SELECT '默认库存标签模板', 9, 'thermal80', '{"elements":[{"id":"lb9_bc","type":"barcode","fieldKey":"sku","label":"SKU 条码","x":4,"y":4,"width":72,"height":14,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb9_pn","type":"text","fieldKey":"product_name","label":"品名","x":4,"y":22,"width":72,"height":10,"fontSize":10,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb9_q","type":"text","fieldKey":"qty","label":"数量","x":4,"y":36,"width":36,"height":7,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false},{"id":"lb9_wh","type":"text","fieldKey":"warehouse","label":"仓库","x":42,"y":36,"width":34,"height":7,"fontSize":9,"fontWeight":"normal","textAlign":"left","border":false}]}', 1
WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'print_templates')
  AND NOT EXISTS (SELECT 1 FROM print_templates WHERE type = 9 AND name = '默认库存标签模板');
