-- 销售单已核实旧容量订正；007/078 已执行，不改写原迁移。
-- 仅处理已确认的 nullable、NULL默认值普通VARCHAR旧形状；其他形状保持。
-- 保留原字符集、排序规则、注释及历史值；兼容两种反斜杠SQL模式。
SET @sale_capacity_283_sql = COALESCE((
  SELECT CONCAT(
    'ALTER TABLE `sale_orders` MODIFY COLUMN `remark` VARCHAR(500) CHARACTER SET `',
    CHARACTER_SET_NAME, '` COLLATE `', COLLATION_NAME, '` DEFAULT NULL COMMENT ',
    IF(FIND_IN_SET('NO_BACKSLASH_ESCAPES', @@SESSION.sql_mode) > 0,
      CONCAT(CHAR(39), REPLACE(COLUMN_COMMENT, CHAR(39), CONCAT(CHAR(39), CHAR(39))), CHAR(39)),
      QUOTE(COLUMN_COMMENT))
  )
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sale_orders'
    AND COLUMN_NAME = 'remark' AND DATA_TYPE = 'varchar'
    AND CHARACTER_MAXIMUM_LENGTH = 30 AND IS_NULLABLE = 'YES'
    AND COLUMN_DEFAULT IS NULL AND EXTRA = '' AND GENERATION_EXPRESSION = ''
    AND CHARACTER_SET_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
    AND COLLATION_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
), 'SELECT 1');
PREPARE sale_capacity_283_stmt FROM @sale_capacity_283_sql;
EXECUTE sale_capacity_283_stmt;
DEALLOCATE PREPARE sale_capacity_283_stmt;

SET @sale_capacity_283_sql = COALESCE((
  SELECT CONCAT(
    'ALTER TABLE `sale_orders` MODIFY COLUMN `receiver_name` VARCHAR(100) CHARACTER SET `',
    CHARACTER_SET_NAME, '` COLLATE `', COLLATION_NAME, '` DEFAULT NULL COMMENT ',
    IF(FIND_IN_SET('NO_BACKSLASH_ESCAPES', @@SESSION.sql_mode) > 0,
      CONCAT(CHAR(39), REPLACE(COLUMN_COMMENT, CHAR(39), CONCAT(CHAR(39), CHAR(39))), CHAR(39)),
      QUOTE(COLUMN_COMMENT))
  )
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sale_orders'
    AND COLUMN_NAME = 'receiver_name' AND DATA_TYPE = 'varchar'
    AND CHARACTER_MAXIMUM_LENGTH = 5 AND IS_NULLABLE = 'YES'
    AND COLUMN_DEFAULT IS NULL AND EXTRA = '' AND GENERATION_EXPRESSION = ''
    AND CHARACTER_SET_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
    AND COLLATION_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
), 'SELECT 1');
PREPARE sale_capacity_283_stmt FROM @sale_capacity_283_sql;
EXECUTE sale_capacity_283_stmt;
DEALLOCATE PREPARE sale_capacity_283_stmt;

SET @sale_capacity_283_sql = COALESCE((
  SELECT CONCAT(
    'ALTER TABLE `sale_orders` MODIFY COLUMN `receiver_phone` VARCHAR(50) CHARACTER SET `',
    CHARACTER_SET_NAME, '` COLLATE `', COLLATION_NAME, '` DEFAULT NULL COMMENT ',
    IF(FIND_IN_SET('NO_BACKSLASH_ESCAPES', @@SESSION.sql_mode) > 0,
      CONCAT(CHAR(39), REPLACE(COLUMN_COMMENT, CHAR(39), CONCAT(CHAR(39), CHAR(39))), CHAR(39)),
      QUOTE(COLUMN_COMMENT))
  )
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sale_orders'
    AND COLUMN_NAME = 'receiver_phone' AND DATA_TYPE = 'varchar'
    AND CHARACTER_MAXIMUM_LENGTH = 11 AND IS_NULLABLE = 'YES'
    AND COLUMN_DEFAULT IS NULL AND EXTRA = '' AND GENERATION_EXPRESSION = ''
    AND CHARACTER_SET_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
    AND COLLATION_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
), 'SELECT 1');
PREPARE sale_capacity_283_stmt FROM @sale_capacity_283_sql;
EXECUTE sale_capacity_283_stmt;
DEALLOCATE PREPARE sale_capacity_283_stmt;

SET @sale_capacity_283_sql = COALESCE((
  SELECT CONCAT(
    'ALTER TABLE `sale_orders` MODIFY COLUMN `receiver_address` VARCHAR(255) CHARACTER SET `',
    CHARACTER_SET_NAME, '` COLLATE `', COLLATION_NAME, '` DEFAULT NULL COMMENT ',
    IF(FIND_IN_SET('NO_BACKSLASH_ESCAPES', @@SESSION.sql_mode) > 0,
      CONCAT(CHAR(39), REPLACE(COLUMN_COMMENT, CHAR(39), CONCAT(CHAR(39), CHAR(39))), CHAR(39)),
      QUOTE(COLUMN_COMMENT))
  )
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sale_orders'
    AND COLUMN_NAME = 'receiver_address' AND DATA_TYPE = 'varchar'
    AND CHARACTER_MAXIMUM_LENGTH = 30 AND IS_NULLABLE = 'YES'
    AND COLUMN_DEFAULT IS NULL AND EXTRA = '' AND GENERATION_EXPRESSION = ''
    AND CHARACTER_SET_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
    AND COLLATION_NAME REGEXP '^[A-Za-z_][A-Za-z0-9_]*$'
), 'SELECT 1');
PREPARE sale_capacity_283_stmt FROM @sale_capacity_283_sql;
EXECUTE sale_capacity_283_stmt;
DEALLOCATE PREPARE sale_capacity_283_stmt;
