const { Router } = require('express')
const ctrl = require('./dashboard.controller')
const { authMiddleware, requirePermission } = require('../../middleware/auth')
const { PERMISSIONS } = require('../../constants/permissions')
const router = Router()
router.use(authMiddleware)
router.get('/summary',    requirePermission(PERMISSIONS.DASHBOARD_VIEW), ctrl.summary)
router.get('/low-stock',  requirePermission(PERMISSIONS.DASHBOARD_VIEW), ctrl.lowStock)
router.get('/trend',      requirePermission(PERMISSIONS.DASHBOARD_VIEW), ctrl.trend)
router.get('/top-stock',  requirePermission(PERMISSIONS.DASHBOARD_VIEW), ctrl.topStock)
module.exports = router
