const { Router } = require('express')
const svc = require('./dashboard.service')
const { successResponse } = require('../../utils/response')
const { authMiddleware, requirePermission } = require('../../middleware/auth')
const { PERMISSIONS } = require('../../constants/permissions')
const router = Router()
router.use(authMiddleware)
router.get('/summary',    requirePermission(PERMISSIONS.DASHBOARD_VIEW), async(req,res,next)=>{ try{return successResponse(res,await svc.getSummary(),'查询成功')}catch(e){next(e)} })
router.get('/low-stock',  requirePermission(PERMISSIONS.DASHBOARD_VIEW), async(req,res,next)=>{ try{return successResponse(res,await svc.getLowStock(+req.query.threshold||10),'查询成功')}catch(e){next(e)} })
router.get('/trend',      requirePermission(PERMISSIONS.DASHBOARD_VIEW), async(req,res,next)=>{ try{return successResponse(res,await svc.getRecentTrend(+req.query.days||7),'查询成功')}catch(e){next(e)} })
router.get('/top-stock',  requirePermission(PERMISSIONS.DASHBOARD_VIEW), async(req,res,next)=>{ try{return successResponse(res,await svc.getTopStockByValue(10),'查询成功')}catch(e){next(e)} })
module.exports = router
