const {Router}=require('express'); const {z}=require('zod')
const ctrl=require('./transfer.controller')
const {authMiddleware, requirePermission}=require('../../middleware/auth')
const { pdaSessionRequired } = require('../../middleware/pdaSession')
const { pdaOnly } = require('../../middleware/pdaOnly')
const { PERMISSIONS } = require('../../constants/permissions')
const { validateBody } = require('../../utils/route')
const router=Router(); router.use(authMiddleware)
const vParams=s=>(req,res,next)=>{const r=s.safeParse(req.params);if(!r.success)return res.status(400).json({success:false,message:r.error.errors.map(e=>e.message).join('；'),data:null});req.params=r.data;next()}
const idParam=z.object({id:z.coerce.number().int().positive('id 必须为正整数')})
const itemSchema=z.object({productId:z.number().int().positive(),productCode:z.string(),productName:z.string(),unit:z.string(),articleNumber:z.string().optional().nullable(),spec:z.string().optional().nullable(),color:z.string().optional().nullable(),quantity:z.number().positive('数量必须大于0'),remark:z.string().optional()})
const createSchema=z.object({fromWarehouseId:z.number().int().positive('请选择调出仓库'),fromWarehouseName:z.string(),toWarehouseId:z.number().int().positive('请选择调入仓库'),toWarehouseName:z.string(),remark:z.string().optional(),items:z.array(itemSchema).min(1,'至少添加一条明细')})
const scanOutSchema=z.object({containerBarcode:z.string().min(1,'请扫描容器条码')})
const scanInSchema=z.object({containerBarcode:z.string().min(1,'请扫描容器条码'),locationId:z.number().int().positive('请扫描库位')})
const forceCloseSchema=z.object({reason:z.string().min(1,'必须填写异常了结原因')})
router.get('/',              requirePermission(PERMISSIONS.TRANSFER_ORDER_VIEW), ctrl.list)
router.get('/:id',           requirePermission(PERMISSIONS.TRANSFER_ORDER_VIEW), vParams(idParam),ctrl.detail)
router.post('/',             requirePermission(PERMISSIONS.TRANSFER_ORDER_CREATE), validateBody(createSchema),ctrl.create)
router.put('/:id',           requirePermission(PERMISSIONS.TRANSFER_ORDER_CREATE), vParams(idParam),validateBody(createSchema),ctrl.update)
router.post('/:id/confirm',  requirePermission(PERMISSIONS.TRANSFER_ORDER_CONFIRM), vParams(idParam),ctrl.confirm)
router.post('/:id/scan-out', requirePermission(PERMISSIONS.TRANSFER_ORDER_EXECUTE), pdaSessionRequired(), pdaOnly, vParams(idParam),validateBody(scanOutSchema),ctrl.scanOut)
router.post('/:id/scan-in',  requirePermission(PERMISSIONS.TRANSFER_ORDER_EXECUTE), pdaSessionRequired(), pdaOnly, vParams(idParam),validateBody(scanInSchema),ctrl.scanIn)
router.post('/:id/cancel',   requirePermission(PERMISSIONS.TRANSFER_ORDER_CANCEL), vParams(idParam),ctrl.cancel)
router.post('/:id/force-close', requirePermission(PERMISSIONS.TRANSFER_ORDER_FORCE_CLOSE), vParams(idParam),validateBody(forceCloseSchema),ctrl.forceCloseInTransit)
module.exports=router
