const { Router } = require('express')
const { z } = require('zod')
const ctrl = require('./stockcheck.controller')
const { authMiddleware, requirePermission } = require('../../middleware/auth')
const { PERMISSIONS } = require('../../constants/permissions')
const router = Router()
const vBody = schema => (req,res,next) => { const r=schema.safeParse(req.body); if(!r.success) return res.status(400).json({success:false,message:r.error.errors.map(e=>e.message).join('；'),data:null}); req.body=r.data; next() }
const createSchema = z.object({ warehouseId:z.number().int().positive('请选择仓库'), warehouseName:z.string(), remark:z.string().optional() })
const updateSchema = z.object({ items:z.array(z.object({ id:z.number().int().positive(), actualQty:z.number().nonnegative('实盘数量不能为负') })).min(1) })
router.use(authMiddleware)
router.get('/',              requirePermission(PERMISSIONS.STOCKCHECK_VIEW), ctrl.list)
router.get('/:id',           requirePermission(PERMISSIONS.STOCKCHECK_VIEW), ctrl.detail)
router.post('/',             requirePermission(PERMISSIONS.STOCKCHECK_CREATE), vBody(createSchema), ctrl.create)
router.put('/:id/items',     requirePermission(PERMISSIONS.STOCKCHECK_UPDATE), vBody(updateSchema),  ctrl.update)
router.post('/:id/submit',   requirePermission(PERMISSIONS.STOCKCHECK_SUBMIT), ctrl.submit)
router.post('/:id/cancel',   requirePermission(PERMISSIONS.STOCKCHECK_CANCEL), ctrl.cancel)
module.exports = router
