export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  ADMIN_PUTAWAY_EXECUTE: 'admin.putaway.execute',
  IMPORT_PRODUCT_EXECUTE: 'import.product.execute',
  IMPORT_STOCK_EXECUTE: 'import.stock.execute',

  PRODUCT_VIEW: 'product.view',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_UPDATE: 'product.update',
  PRODUCT_DELETE: 'product.delete',
  PRODUCT_PRINT_LABEL: 'product.print_label',

  CATEGORY_VIEW: 'category.view',
  CATEGORY_CREATE: 'category.create',
  CATEGORY_UPDATE: 'category.update',
  CATEGORY_DELETE: 'category.delete',

  WAREHOUSE_VIEW: 'warehouse.view',
  WAREHOUSE_CREATE: 'warehouse.create',
  WAREHOUSE_UPDATE: 'warehouse.update',
  WAREHOUSE_DELETE: 'warehouse.delete',

  LOCATION_VIEW: 'location.view',
  LOCATION_CREATE: 'location.create',
  LOCATION_UPDATE: 'location.update',
  LOCATION_DELETE: 'location.delete',

  RACK_VIEW: 'rack.view',
  RACK_CREATE: 'rack.create',
  RACK_UPDATE: 'rack.update',
  RACK_DELETE: 'rack.delete',
  RACK_PRINT_LABEL: 'rack.print_label',

  SUPPLIER_VIEW: 'supplier.view',
  SUPPLIER_CREATE: 'supplier.create',
  SUPPLIER_UPDATE: 'supplier.update',
  SUPPLIER_DELETE: 'supplier.delete',

  CUSTOMER_VIEW: 'customer.view',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_UPDATE: 'customer.update',
  CUSTOMER_DELETE: 'customer.delete',

  CARRIER_VIEW: 'carrier.view',
  CARRIER_CREATE: 'carrier.create',
  CARRIER_UPDATE: 'carrier.update',
  CARRIER_DELETE: 'carrier.delete',

  PRICE_LIST_VIEW: 'price.list.view',
  PRICE_LIST_CREATE: 'price.list.create',
  PRICE_LIST_UPDATE: 'price.list.update',
  PRICE_LIST_DELETE: 'price.list.delete',

  PURCHASE_ORDER_VIEW: 'purchase.order.view',
  PURCHASE_ORDER_CREATE: 'purchase.order.create',
  PURCHASE_ORDER_CONFIRM: 'purchase.order.confirm',
  PURCHASE_ORDER_CANCEL: 'purchase.order.cancel',

  INBOUND_ORDER_VIEW: 'inbound.order.view',
  INBOUND_ORDER_CREATE: 'inbound.order.create',
  INBOUND_ORDER_SUBMIT: 'inbound.order.submit',
  INBOUND_ORDER_AUDIT: 'inbound.order.audit',
  INBOUND_ORDER_CANCEL: 'inbound.order.cancel',
  INBOUND_RECEIVE_EXECUTE: 'inbound.receive.execute',
  INBOUND_PUTAWAY_EXECUTE: 'inbound.putaway.execute',
  INBOUND_PRINT_REPRINT: 'inbound.print.reprint',

  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_CONTAINER_MOVE: 'inventory.container.move',
  INVENTORY_CONTAINER_SPLIT: 'inventory.container.split',
  INVENTORY_TRACE_VIEW: 'inventory.trace.view',

  STOCKCHECK_VIEW: 'stockcheck.view',
  STOCKCHECK_CREATE: 'stockcheck.create',
  STOCKCHECK_UPDATE: 'stockcheck.update',
  STOCKCHECK_SUBMIT: 'stockcheck.submit',
  STOCKCHECK_CANCEL: 'stockcheck.cancel',

  TRANSFER_ORDER_VIEW: 'transfer.order.view',
  TRANSFER_ORDER_CREATE: 'transfer.order.create',
  TRANSFER_ORDER_CONFIRM: 'transfer.order.confirm',
  TRANSFER_ORDER_EXECUTE: 'transfer.order.execute',
  TRANSFER_ORDER_CANCEL: 'transfer.order.cancel',

  SALE_ORDER_VIEW: 'sale.order.view',
  SALE_ORDER_CREATE: 'sale.order.create',
  SALE_ORDER_UPDATE: 'sale.order.update',
  SALE_ORDER_RESERVE: 'sale.order.reserve',
  SALE_ORDER_RELEASE: 'sale.order.release',
  SALE_ORDER_SHIP: 'sale.order.ship',
  SALE_ORDER_CANCEL: 'sale.order.cancel',
  SALE_ORDER_DELETE: 'sale.order.delete',

  RETURN_ORDER_VIEW: 'return.order.view',
  RETURN_ORDER_CREATE: 'return.order.create',
  RETURN_ORDER_CONFIRM: 'return.order.confirm',
  RETURN_ORDER_EXECUTE: 'return.order.execute',
  RETURN_ORDER_CANCEL: 'return.order.cancel',

  PAYMENT_VIEW: 'payment.view',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_EXECUTE: 'payment.execute',

  WAREHOUSE_TASK_VIEW: 'warehouse.task.view',
  WAREHOUSE_TASK_ASSIGN: 'warehouse.task.assign',
  WAREHOUSE_TASK_PICK: 'warehouse.task.pick',
  WAREHOUSE_TASK_CHECK: 'warehouse.task.check',
  WAREHOUSE_TASK_PACK: 'warehouse.task.pack',
  WAREHOUSE_TASK_SORT: 'warehouse.task.sort',
  WAREHOUSE_TASK_CHECK_DONE: 'warehouse.task.check_done',
  WAREHOUSE_TASK_PACK_DONE: 'warehouse.task.pack_done',
  WAREHOUSE_TASK_SHIP: 'warehouse.task.ship',
  WAREHOUSE_TASK_CANCEL: 'warehouse.task.cancel',
  WAREHOUSE_TASK_PRIORITY: 'warehouse.task.priority',
  WAREHOUSE_TASK_DEBUG: 'warehouse.task.debug',

  PICKING_WAVE_VIEW: 'picking.wave.view',
  PICKING_WAVE_MANAGE: 'picking.wave.manage',

  SORTING_BIN_VIEW: 'sorting.bin.view',
  SORTING_BIN_MANAGE: 'sorting.bin.manage',

  SCAN_LOG_VIEW: 'scan.log.view',
  SCAN_LOG_CREATE: 'scan.log.create',

  REPORT_VIEW: 'report.view',

  USER_VIEW: 'user.view',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_RESET_PASSWORD: 'user.reset_password',
  USER_DELETE: 'user.delete',

  ROLE_VIEW: 'role.view',
  ROLE_ASSIGN: 'role.assign',

  SETTINGS_VIEW: 'settings.view',
  SETTINGS_UPDATE: 'settings.update',

  PRINT_JOB_VIEW: 'print.job.view',
  PRINT_JOB_CREATE: 'print.job.create',
  PRINT_JOB_REPRINT: 'print.job.reprint',
  PRINT_JOB_RETRY: 'print.job.retry',
  PRINT_CLIENT_CONSUME: 'print.client.consume',

  PRINT_TEMPLATE_VIEW: 'print.template.view',
  PRINT_TEMPLATE_MANAGE: 'print.template.manage',

  PRINT_PRINTER_VIEW: 'print.printer.view',
  PRINT_PRINTER_MANAGE: 'print.printer.manage',

  AUDIT_LOG_VIEW: 'audit.log.view',
  AUDIT_LOG_CLEAR: 'audit.log.clear',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const PERMISSION_GROUPS: Array<{ group: string; items: Array<{ code: PermissionCode; label: string }> }> = [
  {
    group: '首页',
    items: [{ code: PERMISSIONS.DASHBOARD_VIEW, label: '仪表盘' }],
  },
  {
    group: '平台工具',
    items: [
      { code: PERMISSIONS.ADMIN_PUTAWAY_EXECUTE, label: '管理员补录上架' },
      { code: PERMISSIONS.IMPORT_PRODUCT_EXECUTE, label: '导入商品' },
      { code: PERMISSIONS.IMPORT_STOCK_EXECUTE, label: '导入库存初始化' },
    ],
  },
  {
    group: '主数据',
    items: [
      { code: PERMISSIONS.PRODUCT_VIEW, label: '查看商品' },
      { code: PERMISSIONS.PRODUCT_CREATE, label: '新建商品' },
      { code: PERMISSIONS.PRODUCT_UPDATE, label: '编辑商品' },
      { code: PERMISSIONS.PRODUCT_DELETE, label: '删除商品' },
      { code: PERMISSIONS.CATEGORY_VIEW, label: '查看分类' },
      { code: PERMISSIONS.WAREHOUSE_VIEW, label: '查看仓库' },
      { code: PERMISSIONS.LOCATION_VIEW, label: '查看库位' },
      { code: PERMISSIONS.RACK_VIEW, label: '查看货架' },
      { code: PERMISSIONS.SUPPLIER_VIEW, label: '查看供应商' },
      { code: PERMISSIONS.CUSTOMER_VIEW, label: '查看客户' },
      { code: PERMISSIONS.CARRIER_VIEW, label: '查看承运商' },
      { code: PERMISSIONS.PRICE_LIST_VIEW, label: '查看价格体系' },
    ],
  },
  {
    group: '采购与收货',
    items: [
      { code: PERMISSIONS.PURCHASE_ORDER_VIEW, label: '查看采购单' },
      { code: PERMISSIONS.PURCHASE_ORDER_CREATE, label: '新建采购单' },
      { code: PERMISSIONS.PURCHASE_ORDER_CONFIRM, label: '确认采购单' },
      { code: PERMISSIONS.PURCHASE_ORDER_CANCEL, label: '取消采购单' },
      { code: PERMISSIONS.INBOUND_ORDER_VIEW, label: '查看收货单' },
      { code: PERMISSIONS.INBOUND_ORDER_CREATE, label: '新建收货单' },
      { code: PERMISSIONS.INBOUND_ORDER_SUBMIT, label: '提交收货单' },
      { code: PERMISSIONS.INBOUND_ORDER_AUDIT, label: '审核收货单' },
      { code: PERMISSIONS.INBOUND_RECEIVE_EXECUTE, label: '执行收货' },
      { code: PERMISSIONS.INBOUND_PUTAWAY_EXECUTE, label: '执行上架' },
      { code: PERMISSIONS.INBOUND_PRINT_REPRINT, label: '收货补打' },
    ],
  },
  {
    group: '库存与销售',
    items: [
      { code: PERMISSIONS.INVENTORY_VIEW, label: '查看库存' },
      { code: PERMISSIONS.INVENTORY_ADJUST, label: '库存调整' },
      { code: PERMISSIONS.INVENTORY_CONTAINER_MOVE, label: '容器移库' },
      { code: PERMISSIONS.INVENTORY_CONTAINER_SPLIT, label: '容器拆分' },
      { code: PERMISSIONS.STOCKCHECK_VIEW, label: '查看盘点' },
      { code: PERMISSIONS.STOCKCHECK_CREATE, label: '新建盘点' },
      { code: PERMISSIONS.STOCKCHECK_UPDATE, label: '编辑盘点' },
      { code: PERMISSIONS.STOCKCHECK_SUBMIT, label: '提交盘点' },
      { code: PERMISSIONS.STOCKCHECK_CANCEL, label: '取消盘点' },
      { code: PERMISSIONS.TRANSFER_ORDER_VIEW, label: '查看调拨' },
      { code: PERMISSIONS.TRANSFER_ORDER_CREATE, label: '新建调拨' },
      { code: PERMISSIONS.TRANSFER_ORDER_CONFIRM, label: '确认调拨' },
      { code: PERMISSIONS.TRANSFER_ORDER_EXECUTE, label: '执行调拨' },
      { code: PERMISSIONS.TRANSFER_ORDER_CANCEL, label: '取消调拨' },
      { code: PERMISSIONS.SALE_ORDER_VIEW, label: '查看销售单' },
      { code: PERMISSIONS.SALE_ORDER_CREATE, label: '新建销售单' },
      { code: PERMISSIONS.SALE_ORDER_UPDATE, label: '编辑销售单' },
      { code: PERMISSIONS.SALE_ORDER_RESERVE, label: '销售预占' },
      { code: PERMISSIONS.SALE_ORDER_RELEASE, label: '释放预占' },
      { code: PERMISSIONS.SALE_ORDER_SHIP, label: '发起出库' },
      { code: PERMISSIONS.SALE_ORDER_CANCEL, label: '取消销售单' },
      { code: PERMISSIONS.RETURN_ORDER_VIEW, label: '查看退货单' },
      { code: PERMISSIONS.RETURN_ORDER_CREATE, label: '新建退货单' },
      { code: PERMISSIONS.RETURN_ORDER_CONFIRM, label: '确认退货单' },
      { code: PERMISSIONS.RETURN_ORDER_EXECUTE, label: '执行退货单' },
      { code: PERMISSIONS.RETURN_ORDER_CANCEL, label: '取消退货单' },
      { code: PERMISSIONS.PAYMENT_VIEW, label: '查看账款' },
      { code: PERMISSIONS.PAYMENT_CREATE, label: '新建账款' },
      { code: PERMISSIONS.PAYMENT_EXECUTE, label: '登记收付款' },
    ],
  },
  {
    group: '仓库作业',
    items: [
      { code: PERMISSIONS.WAREHOUSE_TASK_VIEW, label: '查看仓库任务' },
      { code: PERMISSIONS.WAREHOUSE_TASK_ASSIGN, label: '分配仓库任务' },
      { code: PERMISSIONS.WAREHOUSE_TASK_PICK, label: '执行拣货' },
      { code: PERMISSIONS.WAREHOUSE_TASK_CHECK, label: '执行复核' },
      { code: PERMISSIONS.WAREHOUSE_TASK_PACK, label: '执行打包' },
      { code: PERMISSIONS.WAREHOUSE_TASK_SHIP, label: '执行出库' },
      { code: PERMISSIONS.PICKING_WAVE_VIEW, label: '查看波次' },
      { code: PERMISSIONS.PICKING_WAVE_MANAGE, label: '管理波次' },
      { code: PERMISSIONS.SORTING_BIN_VIEW, label: '查看分拣格' },
      { code: PERMISSIONS.SORTING_BIN_MANAGE, label: '管理分拣格' },
      { code: PERMISSIONS.SCAN_LOG_VIEW, label: '查看扫码日志' },
      { code: PERMISSIONS.SCAN_LOG_CREATE, label: '记录扫码日志' },
    ],
  },
  {
    group: '打印与平台',
    items: [
      { code: PERMISSIONS.PRINT_JOB_VIEW, label: '查看打印任务' },
      { code: PERMISSIONS.PRINT_JOB_CREATE, label: '创建打印任务' },
      { code: PERMISSIONS.PRINT_JOB_REPRINT, label: '补打打印任务' },
      { code: PERMISSIONS.PRINT_TEMPLATE_VIEW, label: '查看打印模板' },
      { code: PERMISSIONS.PRINT_TEMPLATE_MANAGE, label: '管理打印模板' },
      { code: PERMISSIONS.PRINT_PRINTER_VIEW, label: '查看打印机' },
      { code: PERMISSIONS.PRINT_PRINTER_MANAGE, label: '管理打印机' },
      { code: PERMISSIONS.USER_VIEW, label: '查看用户' },
      { code: PERMISSIONS.USER_CREATE, label: '新建用户' },
      { code: PERMISSIONS.USER_UPDATE, label: '编辑用户' },
      { code: PERMISSIONS.USER_RESET_PASSWORD, label: '重置密码' },
      { code: PERMISSIONS.ROLE_VIEW, label: '查看角色权限' },
      { code: PERMISSIONS.ROLE_ASSIGN, label: '配置角色权限' },
      { code: PERMISSIONS.SETTINGS_VIEW, label: '查看系统设置' },
      { code: PERMISSIONS.SETTINGS_UPDATE, label: '修改系统设置' },
      { code: PERMISSIONS.AUDIT_LOG_VIEW, label: '查看操作日志' },
      { code: PERMISSIONS.AUDIT_LOG_CLEAR, label: '清理操作日志' },
      { code: PERMISSIONS.REPORT_VIEW, label: '查看报表' },
    ],
  },
]
